{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-censusapi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/censusapi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/censusapi/censusapi_{{ version }}.tar.gz
  sha256: 1998a52c533c315510799b7caaca0f8a06a5206c030ffd07f3cb8155a7695cf3

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-jsonlite
  run:
    - r-base
    - r-httr
    - r-jsonlite

test:
  commands:
    - $R -e "library('censusapi')"           # [not win]
    - "\"%R%\" -e \"library('censusapi')\""  # [win]

about:
  home: https://github.com/hrecht/censusapi
  license: GPL-3.0-only
  summary: A wrapper for the U.S. Census Bureau APIs that returns data frames of Census data and metadata. Available datasets include the Decennial Census, American Community Survey, Small Area Health Insurance Estimates, Small Area Income and Poverty Estimates, Population Estimates and Projections, and more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
